sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**,**/test-results/**,**/public/**,**/prisma/migrations/**
sonar.coverage.exclusions=src/app/**,src/messages/**,src/**/*.tsx,src/**/*.d.ts
